import { BackgroundImage, Center, Image, SimpleGrid, Title, useMantineTheme } from '@mantine/core'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect } from 'react'
import { Cursor } from '../components/Cursor'
import { Level1 } from '../components/level1/Level1'
import { StatsState, useStatsStore } from '../store/zustandStore'
import { homeStyles } from '../styles/home'

const Home: NextPage = () => {
   const theme = useMantineTheme()
   // TODO: this TS state is messed up.
   const patchesMowed = useStatsStore((state: any) => state.patchesMowed)
   return (
      <div
         style={{
            display: 'flex',
            justifyContent: 'center',
            height: '100vh',
            width: '100vw',
            alignItems: 'center',
         }}
      >
         <Head>
            <title>LAWNMOWER 5000</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
         </Head>

         <div
            style={{
               position: 'relative',
               alignItems: 'center',
               cursor: 'none',
               justifyContent: 'center',
               display: 'flex',
               height: '500px',
               width: '800px',
            }}
         >
            <Image
               alt='logo'
               src='/textures/logo.png'
               height='200px'
               width='450px'
               style={{ position: 'absolute', top: '-200px', zIndex: 999 }}
            />
            <Level1 />

            <div style={{ position: 'absolute', bottom: '-30px', width: '800px' }}>
               <Title style={{ color: theme.colors.yellow as any }} order={3}>
                  Patches Mowed: {patchesMowed}
               </Title>
            </div>
         </div>
      </div>
   )
}

export default Home
